asdf

diff --git a/.github/actions/install-briefcase/action.yml b/.github/actions/install-briefcase/action.yml
--- a/.github/actions/install-briefcase/action.yml
+++ b/.github/actions/install-briefcase/action.yml
@@ -36,10 +36,8 @@ runs:
       id: briefcase-override
       shell: bash
       run: |
-        set +o pipefail  # prevent grep failing the step if repo/ref isn't found
+        #set +o pipefail  # prevent grep failing the step if repo/ref isn't found
         
-        man perl
-
         # Source version from Body of PR
         PR_BODY="${{ inputs.testing-pr-body }}"
         if [ -z "${PR_BODY}" ]; then
